
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ricardo
 */
public class Tgrafica extends javax.swing.JFrame {
   
    
    /**
     * Creates new form Tgrafica
     */
    
    
    public Tgrafica() {
        super("T Grafica");
        setSize (480,200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
        saldard.setEnabled(false);
        saldarh.setEnabled(false);
        balanced.setEnabled(false);
        balanceh.setEnabled(false);
        balance.setEnabled(false);
        saldar.setEnabled(false);
        cierred.setEnabled(false);
        cierreh.setEnabled(false);
    }
    //Dibujar Linea
    void dibujarLinea(Graphics g){
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawLine(40,160,600,160);//Linea Horizontal
        g2d.drawLine(300,600,300,120); //Linea Vertical
        g2d.drawLine(40,400,600,400); //Linea de Saldar
        g2d.drawLine(40,490,600,490);//Linea del Balance
        
        g2d.drawLine(40, 550, 600, 550); //Cerrar Cuenta
        g2d.drawLine(40, 560, 600, 560);
    }
    
   
    @Override
    public void paint(Graphics g){
        super.paint(g);
        dibujarLinea(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cuentas = new javax.swing.JComboBox();
        abrird = new javax.swing.JTextField();
        abrirh = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();
        h3 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        saldarh = new javax.swing.JTextField();
        saldard = new javax.swing.JTextField();
        balanced = new javax.swing.JTextField();
        balanceh = new javax.swing.JTextField();
        saldar = new javax.swing.JButton();
        balance = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        cierred = new javax.swing.JTextField();
        cierreh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel1.setText("T Grafica");
        JLabel1.setName(""); // NOI18N

        jLabel2.setText("Debe");

        jLabel3.setText("Haber");

        cuentas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elija una Cuenta", "Acreedores", "Bonificacion Incentivo", "Caja", "Capital", "Clientes", "Comisiones", "Compras", "Credito Fiscal", "Cuentas por cobrar", "Cuentas por pagar", "Debito Fiscal", "Hipotecas", "Mobiliario y Equipo", "IVA Acreedor", "IVA Deudor", "Maquinaria", "Mercaderia", "Proveedores", "Sueldos y Salarios", "Ventas" }));
        cuentas.setName("cuentas"); // NOI18N
        cuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentasActionPerformed(evt);
            }
        });

        saldar.setText("Saldar Cuenta");
        saldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldarActionPerformed(evt);
            }
        });

        balance.setText("Balancear Cuenta");
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setText("Fila para abrir la cuenta");

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(JLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cierred)
                                    .addComponent(balanced)
                                    .addComponent(abrird, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(d1)
                                    .addComponent(d2)
                                    .addComponent(d3)
                                    .addComponent(saldard))))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cierreh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(balanceh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(abrirh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(saldarh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(exit)
                                            .addComponent(balance)
                                            .addComponent(saldar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(limpiar)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 85, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2)
                        .addGap(335, 335, 335)
                        .addComponent(jLabel3)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JLabel1)
                .addGap(18, 18, 18)
                .addComponent(cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrirh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldarh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cierred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cierreh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(limpiar)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentasActionPerformed
        // TODO add your handling code here:
        String selectedValue = cuentas.getSelectedItem().toString();
        
        switch(selectedValue){
            case "Elija una Cuenta":
                abrirh.setEnabled(true);
                abrird.setEnabled(true);
            break; 
            case "Acreedores":
                abrirh.setEnabled(true);
                abrird.setEnabled(false);
            break;
            case "Bonificacion Incentivo":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;     
            case "Caja":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break; 
            case "Capital":
                abrird.setEnabled(false);  
                abrirh.setEnabled(true);
            break;    
            case "Clientes":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;    
            case "Comisiones":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Compras":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Credito Fiscal":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Cuentas por cobrar":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Cuentas por pagar":
                abrirh.setEnabled(true);
                abrird.setEnabled(false);
            break;
            case "Debito Fiscal":
                abrirh.setEnabled(true);
                abrird.setEnabled(false);
            break;
            case "Hipotecas":
                abrirh.setEnabled(true);
                abrird.setEnabled(false);
            break;
            case "Mobiliario y Equipo":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "IVA Acreedor":
                abrirh.setEnabled(true);
                abrird.setEnabled(false);
            break;
            case "IVA Deudor":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Maquinaria":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Mercaderia":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Proveedores":
                abrirh.setEnabled(true);
                abrird.setEnabled(false);
            break;
            case "Sueldos y Salarios":
                abrirh.setEnabled(false);
                abrird.setEnabled(true);
            break;
            case "Ventas":
                abrirh.setEnabled(true);
                abrird.setEnabled(false);
            break;
                
        }
        saldar.setEnabled(true);
       
    }//GEN-LAST:event_cuentasActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void saldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldarActionPerformed
        // TODO add your handling code here:
        //Manejo de exceocpcion donde no se llenen todos los campos
        if(d1.getText().equals("")){
            d1.setText("0");
        }
        if(d2.getText().equals("")){
            d2.setText("0");
        }
        if(d3.getText().equals("")){
            d3.setText("0");
        }
        if(h1.getText().equals("")){
            h1.setText("0");
        }
        if(h2.getText().equals("")){
            h2.setText("0");
        }
        if(h3.getText().equals("")){
            h3.setText("0");
        }
        
        String debe1 = d1.getText();
        String debe2 = d2.getText();
        String debe3 = d3.getText();
        String haber1 = h1.getText();
        String haber2 = h2.getText();
        String haber3 = h3.getText();
        String abrir_debe, abrir_haber;
        double ad=0,ah=0;
        
        double d1 = Double.parseDouble(debe1);
        double d2 = Double.parseDouble(debe2);
        double d3 = Double.parseDouble(debe3);
        double h1 = Double.parseDouble(haber1);
        double h2 = Double.parseDouble(haber2);
        double h3 = Double.parseDouble(haber3);
        //If para debe
        if(!abrird.isEnabled()){
            abrird.setText("0");
            abrir_debe = abrird.getText();
            ad = Double.parseDouble(abrir_debe);
        }
        else{
            abrir_debe = abrird.getText();
            ad = Double.parseDouble(abrir_debe);
        }
        
        //If para haber
        if(!abrirh.isEnabled()){
            abrirh.setText("0");
            abrir_haber = abrirh.getText();
            ah = Double.parseDouble(abrir_haber);
        }
        else{
            abrir_haber =abrirh.getText();
            ah = Double.parseDouble(abrir_haber);
        }
        
        
        
        double saldo_debe = ad+d1+d2+d3;
        double saldo_haber = ah+h1+h2+h3;
        
        String sd = Double.toString(saldo_debe);
        String sh = Double.toString(saldo_haber);
        
        //saldard.setEnabled(true);
        //saldarh.setEnabled(true);
        
        saldard.setText(sd);
        saldarh.setText(sh);
        
        balance.setEnabled(true);
        
    }//GEN-LAST:event_saldarActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
        //Si abre del lado del debe
        if(!abrirh.isEnabled()){
            String bd = saldard.getText();
            balanced.setText("");
        
            String bh = saldarh.getText();
            double saldoh = Double.parseDouble(bh);
            double saldod = Double.parseDouble(bd);
            double diferencia = saldod - saldoh;
            
            String dif = Double.toString(diferencia);
            balanceh.setText(dif);
            cierred.setText(bd);
            cierreh.setText(bd);
        }
        //Si abre del lado del haber
        else if(!abrird.isEnabled()){
            String bh = saldarh.getText();
            balanceh.setText("");
            
            String bd = saldard.getText();
            double saldoh = Double.parseDouble(bh);
            double saldod = Double.parseDouble(bd);
            double diferencia = saldoh - saldod;
            
            
            String dif = Double.toString(diferencia);
            balanced.setText(dif);
            cierred.setText(bh);
            cierreh.setText(bh);
            
        }
        
        
        
    }//GEN-LAST:event_balanceActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        abrird.setText("");
        abrirh.setText("");
        d1.setText("");
        d2.setText("");
        d3.setText("");
        h1.setText("");
        h2.setText("");
        h3.setText("");
        saldard.setText("");
        saldarh.setText("");
        balanced.setText("");
        balanceh.setText("");
        cierred.setText("");
        cierreh.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tgrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tgrafica().setVisible(true);
                
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JTextField abrird;
    private javax.swing.JTextField abrirh;
    private javax.swing.JButton balance;
    private javax.swing.JTextField balanced;
    private javax.swing.JTextField balanceh;
    private javax.swing.JTextField cierred;
    private javax.swing.JTextField cierreh;
    private javax.swing.JComboBox cuentas;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JButton exit;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton saldar;
    private javax.swing.JTextField saldard;
    private javax.swing.JTextField saldarh;
    // End of variables declaration//GEN-END:variables
}
